export const Z = {
  bg: "#09090d", bg2: "#0c0e15", bg3: "#131720",
  border: "#14161f", border2: "#1d2235",
  text: "#e2e8f0", textMid: "#4a5568", textDim: "#23293a",
  accent: "#6366f1",
  fontMono: "'DM Mono','Fira Code',monospace",
  fontAr: "'Tajawal',Tahoma,Arial,sans-serif",
};

export const ALERT = {
  error:   { border: "rgba(239,68,68,0.3)",   bg: "rgba(239,68,68,0.07)",   color: "#ef4444", icon: "⛔" },
  warning: { border: "rgba(245,158,11,0.3)",  bg: "rgba(245,158,11,0.07)",  color: "#f59e0b", icon: "⚠" },
  info:    { border: "rgba(99,102,241,0.25)", bg: "rgba(99,102,241,0.07)",  color: "#818cf8", icon: "ℹ" },
  verify:  { border: "rgba(6,182,212,0.3)",   bg: "rgba(6,182,212,0.07)",   color: "#06b6d4", icon: "✦" },
  success: { border: "rgba(16,185,129,0.3)",  bg: "rgba(16,185,129,0.07)",  color: "#10b981", icon: "✓" },
  tip:     { border: "rgba(167,139,250,0.3)", bg: "rgba(167,139,250,0.07)", color: "#a78bfa", icon: "◈" },
};

export const mk = (rtl) => ({
  app:    {display:"flex",height:"100vh",background:Z.bg,fontFamily:rtl?Z.fontAr:Z.fontMono,color:Z.text,overflow:"hidden",direction:rtl?"rtl":"ltr"},
  sb:     {width:252,minWidth:252,background:Z.bg,borderRight:rtl?"none":"1px solid "+Z.border,borderLeft:rtl?"1px solid "+Z.border:"none",display:"flex",flexDirection:"column",overflow:"hidden"},
  sbHead: {padding:"16px 13px 10px",borderBottom:"1px solid "+Z.border},
  logo:   {fontSize:13,fontWeight:700,letterSpacing:rtl?"0":"0.1em",color:"#c7d2fe",textTransform:"uppercase",display:"flex",alignItems:"center",gap:8,flexDirection:rtl?"row-reverse":"row"},
  mark:   {width:22,height:22,background:"linear-gradient(135deg,#6366f1,#a78bfa)",borderRadius:5,display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:900,color:"white",flexShrink:0},
  newBtn: {width:"100%",marginTop:10,padding:"7px 10px",background:Z.bg3,border:"1px solid "+Z.border2,borderRadius:7,color:Z.accent,fontSize:rtl?13:11,cursor:"pointer",display:"flex",alignItems:"center",gap:5,fontFamily:"inherit",fontWeight:600,transition:"all 0.15s",justifyContent:rtl?"flex-end":"flex-start"},
  srchW:  {padding:"7px 12px 4px"},
  srch:   {width:"100%",padding:"6px 9px",background:Z.bg2,border:"1px solid "+Z.border,borderRadius:6,color:Z.textMid,fontSize:rtl?13:11,fontFamily:"inherit",outline:"none",boxSizing:"border-box",textAlign:rtl?"right":"left"},
  list:   {flex:1,overflowY:"auto",padding:"3px 7px"},
  grpLbl: {fontSize:9,fontWeight:700,letterSpacing:rtl?"0":"0.15em",color:Z.textDim,textTransform:"uppercase",padding:"7px 7px 2px",textAlign:rtl?"right":"left"},
  item:   (on)=>({padding:"7px 8px",borderRadius:6,cursor:"pointer",marginBottom:1,background:on?Z.bg3:"transparent",border:on?"1px solid "+Z.border2:"1px solid transparent",transition:"all 0.1s"}),
  iName:  (on)=>({fontSize:rtl?13:12,color:on?Z.text:Z.textMid,fontWeight:on?600:400,display:"block",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",textAlign:rtl?"right":"left"}),
  iMeta:  {display:"flex",alignItems:"center",gap:5,marginTop:2,flexDirection:rtl?"row-reverse":"row"},
  dot:    (c)=>({width:5,height:5,borderRadius:"50%",background:c,flexShrink:0}),
  mt:     {fontSize:9,color:Z.textDim},
  sbFt:   {padding:"7px 13px 10px",borderTop:"1px solid "+Z.border},
  ftTxt:  {fontSize:9,color:Z.textDim,letterSpacing:"0.07em",textAlign:rtl?"right":"left"},
  main:   {flex:1,display:"flex",flexDirection:"column",overflow:"hidden"},
  tb:     {height:50,borderBottom:"1px solid "+Z.border,display:"flex",alignItems:"center",padding:"0 18px",gap:9,flexShrink:0,background:Z.bg,flexDirection:rtl?"row-reverse":"row"},
  tbTitle:{fontSize:13,fontWeight:600,color:Z.text,flex:1,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",textAlign:rtl?"right":"left"},
  tbActs: {display:"flex",gap:6,alignItems:"center",flexShrink:0,flexDirection:rtl?"row-reverse":"row"},
  btn:    (v="gh")=>{const m={primary:{bg:Z.accent,br:Z.accent,col:"white"},danger:{bg:"rgba(239,68,68,0.08)",br:"rgba(239,68,68,0.25)",col:"#ef4444"},ai:{bg:"rgba(99,102,241,0.1)",br:"rgba(99,102,241,0.35)",col:"#818cf8"},gh:{bg:Z.bg3,br:Z.border2,col:"#8892a0"}};const s=m[v]||m.gh;return{padding:v==="primary"?"7px 14px":"6px 11px",background:s.bg,border:"1px solid "+s.br,borderRadius:7,color:s.col,fontSize:rtl?13:11,cursor:"pointer",fontFamily:"inherit",fontWeight:500,display:"flex",alignItems:"center",gap:5,transition:"all 0.15s",whiteSpace:"nowrap"};},
  body:   {flex:1,display:"flex",overflow:"hidden",flexDirection:rtl?"row-reverse":"row"},
  lnav:   {width:192,minWidth:192,borderRight:rtl?"none":"1px solid "+Z.border,borderLeft:rtl?"1px solid "+Z.border:"none",display:"flex",flexDirection:"column",background:"#07080c",overflowY:"auto"},
  lnavTop:{flex:1,padding:"12px 7px 6px"},
  lnavLbl:{fontSize:9,fontWeight:700,letterSpacing:rtl?"0":"0.15em",color:"#1a1e2a",textTransform:"uppercase",padding:"0 7px 6px",textAlign:rtl?"right":"left"},
  lnavItm:(on)=>({padding:"6px 9px",borderRadius:5,cursor:"pointer",marginBottom:1,background:on?Z.bg3:"transparent",color:on?Z.text:"#2e3a4a",fontSize:rtl?13:11,display:"flex",alignItems:"center",gap:7,transition:"all 0.1s",border:on?"1px solid "+Z.border2:"1px solid transparent",flexDirection:rtl?"row-reverse":"row"}),
  lnavIco:{fontSize:11,opacity:0.7,width:13,textAlign:"center",flexShrink:0},
  lnavBdg:(col="#6366f1")=>({marginLeft:rtl?"0":"auto",marginRight:rtl?"auto":"0",fontSize:9,background:col+"22",color:col,padding:"1px 5px",borderRadius:8,border:"1px solid "+col+"33"}),
  steps:  {padding:"10px 13px 14px",borderTop:"1px solid "+Z.border},
  stpLbl: {fontSize:9,fontWeight:700,letterSpacing:rtl?"0":"0.15em",color:"#1a1e2a",textTransform:"uppercase",marginBottom:10,textAlign:rtl?"right":"left"},
  stpRow: {display:"flex",alignItems:"flex-start",gap:9,position:"relative",flexDirection:rtl?"row-reverse":"row"},
  stpLine:(done)=>({position:"absolute",[rtl?"right":"left"]:7,top:18,width:2,bottom:-12,background:done?"#6366f1":Z.border,transition:"background 0.4s"}),
  stpCirc:(on,done,col)=>({width:16,height:16,borderRadius:"50%",flexShrink:0,border:`2px solid ${on||done?col:Z.border2}`,background:on?col:done?col+"44":"transparent",display:"flex",alignItems:"center",justifyContent:"center",marginTop:1,transition:"all 0.3s",cursor:"pointer",zIndex:1}),
  stpTxt: (on,col)=>({fontSize:rtl?12:11,color:on?col:"#2e3a4a",fontWeight:on?600:400,lineHeight:1.2,textAlign:rtl?"right":"left"}),
  stpDesc:{fontSize:9,color:"#1a1e2a",marginTop:1,textAlign:rtl?"right":"left"},
  form:   {flex:1,overflowY:"auto",padding:"22px 30px"},
  sTitle: {fontSize:15,fontWeight:700,color:Z.text,marginBottom:3,textAlign:rtl?"right":"left"},
  sDesc:  {fontSize:rtl?13:11,color:"#2e3a4a",marginBottom:16,lineHeight:1.5,textAlign:rtl?"right":"left"},
  fg:     {marginBottom:16},
  lbl:    {fontSize:rtl?12:10,fontWeight:700,letterSpacing:rtl?"0":"0.1em",color:"#2e3a4a",textTransform:"uppercase",display:"block",marginBottom:5,textAlign:rtl?"right":"left"},
  hint:   {fontSize:rtl?12:10,color:"#1a1e2a",marginBottom:5,lineHeight:1.5,textAlign:rtl?"right":"left"},
  inp:    {width:"100%",padding:"8px 11px",background:Z.bg2,border:"1px solid "+Z.border,borderRadius:7,color:Z.text,fontSize:rtl?13:12,fontFamily:"inherit",outline:"none",boxSizing:"border-box",transition:"border-color 0.15s",textAlign:rtl?"right":"left",direction:rtl?"rtl":"ltr"},
  sel:    {width:"100%",padding:"8px 11px",background:Z.bg2,border:"1px solid "+Z.border,borderRadius:7,color:Z.text,fontSize:rtl?13:12,fontFamily:"inherit",outline:"none",appearance:"none",boxSizing:"border-box",cursor:"pointer",textAlign:rtl?"right":"left",direction:rtl?"rtl":"ltr"},
  txa:    {width:"100%",padding:"9px 11px",background:Z.bg2,border:"1px solid "+Z.border,borderRadius:7,color:Z.text,fontSize:rtl?13:12,fontFamily:"inherit",outline:"none",boxSizing:"border-box",resize:"vertical",lineHeight:1.8,transition:"border-color 0.15s",textAlign:rtl?"right":"left",direction:rtl?"rtl":"ltr"},
  g2:     {display:"grid",gridTemplateColumns:"1fr 1fr",gap:13},
  pills:  {display:"flex",flexWrap:"wrap",gap:5,justifyContent:rtl?"flex-end":"flex-start"},
  pill:   (on,col="#6366f1")=>({padding:"4px 11px",borderRadius:20,fontSize:rtl?13:11,cursor:"pointer",border:"1px solid "+(on?col:Z.border2),background:on?col+"20":"transparent",color:on?col:"#2e3a4a",transition:"all 0.15s",fontFamily:"inherit"}),
  card:   {background:Z.bg2,border:"1px solid "+Z.border,borderRadius:9,padding:"13px",marginBottom:10},
  cTitle: (col)=>({fontSize:rtl?12:10,fontWeight:700,color:col,letterSpacing:rtl?"0":"0.08em",marginBottom:10,textTransform:"uppercase",textAlign:rtl?"right":"left"}),
  chkItm: (on)=>({display:"flex",alignItems:"flex-start",gap:8,padding:"7px 9px",borderRadius:5,marginBottom:3,cursor:"pointer",background:on?"rgba(99,102,241,0.05)":"transparent",border:on?"1px solid rgba(99,102,241,0.15)":"1px solid transparent",transition:"all 0.1s",flexDirection:rtl?"row-reverse":"row"}),
  chkBox: (on)=>({width:15,height:15,borderRadius:4,flexShrink:0,marginTop:1,background:on?"#6366f1":"transparent",border:on?"1px solid #6366f1":"1px solid #23293a",display:"flex",alignItems:"center",justifyContent:"center",transition:"all 0.15s"}),
  divider:{borderTop:"1px solid "+Z.border,margin:"18px 0"},
  xbtn:   {width:25,height:25,display:"flex",alignItems:"center",justifyContent:"center",background:"transparent",border:"1px solid "+Z.border,borderRadius:5,color:"#2e3a4a",cursor:"pointer",fontSize:10,fontFamily:"inherit",flexShrink:0},
  hld:    {background:"rgba(99,102,241,0.05)",border:"1px solid rgba(99,102,241,0.18)",borderRadius:8,padding:"12px 13px",marginBottom:18},
  tag:    (sid)=>{const sm={"in_progress":{color:"#F59E0B",bg:"rgba(245,158,11,0.12)"},"finalized":{color:"#10B981",bg:"rgba(16,185,129,0.12)"},"go_to_poc":{color:"#6366F1",bg:"rgba(99,102,241,0.12)"}};const s=sm[sid]||{};return{display:"inline-flex",alignItems:"center",gap:4,padding:"2px 7px",borderRadius:4,fontSize:10,fontWeight:600,color:s.color,background:s.bg,letterSpacing:"0.04em"};},
  rBadge: (col)=>({display:"inline-flex",alignItems:"center",padding:"2px 7px",borderRadius:4,fontSize:10,fontWeight:600,color:col,background:col+"18",marginLeft:rtl?0:8,marginRight:rtl?8:0}),
  empty:  {flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:10},
  subCard:{background:"rgba(99,102,241,0.04)",border:"1px solid rgba(99,102,241,0.12)",borderRadius:7,padding:"12px",marginTop:10},
});
